### PR TITLE
Fix chat focus behavior to allow copy/paste from messages

### LINKED ISSUE #267: Remove the `onclick` handler on `ChatWidget`?
Currently clicking on the chat brings the focus to the input.

This seems to be coming from here in the code base:

https://github.com/jupyterlab/jupyter-chat/blob/98898f104681b85808a477af2b91d10a3a49745c/packages/jupyter-chat/src/widgets/chat-widget.tsx#L43

This leads to the following behavior, making it difficult to copy past content from the chat:

https://github.com/user-attachments/assets/9f464112-e343-406b-bcd5-af83696b256b

Should this be kept, or removed?

### PR DESCRIPTION
**Pull request by nakul-py**
Previously, clicking anywhere in the chat panel forced focus onto the input (`this.node.onclick = () => this.model.input.focus();`). This made it difficult to select or copy text from the chat history, since every click redirected focus.

Now we check if the user has selected text input loses focus, click on `button`,` interactive elements`, `<details>`, `<summary>` and else work like before

https://github.com/user-attachments/assets/4f9b995e-01f2-4b29-be33-ed6597782000

Closes #267

### CODE REVIEW

File: packages/jupyter-chat/src/widgets/chat-widget.tsx [hunk 1]
```diff
@@ -40,7 +41,12 @@ export class ChatWidget extends ReactWidget {
 
     this._chatOptions = options;
     this.id = `jupyter-chat::widget::${options.model.name}`;
-    this.node.onclick = () => this.model.input.focus();
+    this.node.addEventListener('click', (event: MouseEvent) => {
+      const target = event.target as HTMLElement;
+      if (!target.closest(`.${MESSAGE_CLASS}`)) {
```
Comment (brichet) [inline packages/jupyter-chat/src/widgets/chat-widget.tsx:46]: Perhaps we could check if some text is selected in the message, and avoid focusing on the input if some text is selected.

**Review by brichet — COMMENTED** [review]
Thanks @nakul-py for working on this.

I have some comment below, let me know if it sound reasonable.

File: packages/jupyter-chat/src/widgets/chat-widget.tsx (hunk 1 above)
Comment (brichet) [reply packages/jupyter-chat/src/widgets/chat-widget.tsx]: The idea was to focus the input when clicking anywhere on the chat (including messages), except if this click result in a selection in the message.

Maybe something like the following (to be tested):

```ts
  const message = target.closest(`.${MESSAGE_CLASS}`);
  if (message) {
    const selection = window.getSelection();

    // Do not focus the input if the clicked message has selected text
    if (
      selection &&
      message.contains(selection.anchorNode) &&
      selection.toString().trim() !== ''
    ) {
      return;
    }
  }
  this.model.input.focus();
```

Comment (jtpio) [reply packages/jupyter-chat/src/widgets/chat-widget.tsx]: > The idea was to focus the input when clicking anywhere on the chat (including messages), except if this click result in a selection in the message.

Don't we also want to allow for clicking on buttons that may be inlined in the chat directly or in `<details>` sections, without forcing the focus on the text area?

**Comment by jtpio** [comment]
Wondering if we really need to force the focus to the chat area at all?

As a user, it can be frustrating if the application forces the focus to be somewhere else than where we want it to be.

File: packages/jupyter-chat/src/widgets/chat-widget.tsx [hunk 2]
```diff
@@ -40,7 +41,29 @@ export class ChatWidget extends ReactWidget {
...
     this._chatOptions = options;
     this.id = `jupyter-chat::widget::${options.model.name}`;
-    this.node.onclick = () => this.model.input.focus();
+    this.node.addEventListener('click', (event: MouseEvent) => {
+      const target = event.target as HTMLElement;
+      if (
+        target.closest('button, a, input, textarea, select, summary, details')
+      ) {
+        return;
+      }
```
Comment (brichet) [inline packages/jupyter-chat/src/widgets/chat-widget.tsx:49]: Thinking again about it, a more generic way could be to check if the current active element is on the chat, instead of checking if the target isl focusable element. Something like:

```suggestion
      if (this.node.contains(document.activeElement)) {
        return;
      }
```

That way we ensure that the input get focussed (and the tracker updates the current chat) only if the click occurs in a non-focusable element.

Comment (brichet) [reply packages/jupyter-chat/src/widgets/chat-widget.tsx]: Thanks @nakul-py for updating it quickly.
